version: '2'

services:
        mvsd:
                image: cangr/mvsd:0.7.5
                environment:
                        - ENVIRONMENT=-t
        mongodb:
                image: library/mongo
        router:
                build: wamp/router
                ports:
                        - "8080:8080"
        provider:
                build: wamp/provider
                environment:
                        - ROUTER_URL=ws://router:8080/ws
                        - REALM=realm1
                        - WS_USER=listingprovider
                        - WS_SECRET=supersecret
                        - PROVIDE_TASK=listings
                        - MONGO_HOST=mongodb
                        - LISTINGS_TIMER=5000
