version: '2'

services:
        redis:
                image: redis
        mvsd:
                image: mvsorg/mvsd
                environment:
                        - ENVIRONMENT=-t
        mongodb:
                image: library/mongo
        router:
                build: wamp/router
                restart: always
                ports:
                        - "8080:8080"
        provider:
                build: wamp/provider
                restart: always
                environment:
                        - ROUTER_URL=ws://router:8080/ws
                        - REALM=realm1
                        - WS_USER=listingprovider
                        - WS_SECRET=supersecret
                        - PROVIDE_TASK=listings
                        - MONGO_HOST=mongodb
                links:
                        - router
                        - mongodb
        api:
                build: api
                restart: always
                environment:
                        - MONGO_HOST=mongodb
                        - REDIS_HOST=redis
                links:
                        - redis
                        - mongodb
                ports:
                        - "80:80"
